// Generated by CoffeeScript 1.6.3

/*
  * GET home page.
 */

(function() {
  exports.index = function(req, res) {
    return res.render('index', {
      title: 'Lingo Translation Machine'
    });
  };

}).call(this);
