// Generated by CoffeeScript 1.6.3

/*
  * Module dependencies.
 */

(function() {
  var BeGlobal, app, beglobal, express, http, path, routes;

  express = require('express');

  routes = require('./../routes');

  http = require('http');

  path = require('path');

  BeGlobal = require('node-beglobal');

  app = express();

  app.set('port', process.env.PORT || 3000);

  app.set('views', __dirname + '/../views');

  app.set('view engine', 'jade');

  app.use(express.favicon());

  app.use(express.logger('dev'));

  app.use(express.bodyParser());

  app.use(express.methodOverride());

  app.use(app.router);

  app.use(express["static"](path.join(__dirname, '../public')));

  beglobal = new BeGlobal.BeglobalAPI({
    api_token: '%2FxBNOQ97cfhhUBCDYpVq0A%3D%3D'
  });

  if ('development' === app.get('env')) {
    app.use(express.errorHandler());
  }

  app.get('/', routes.index);

  app.get('/quiz', function(req, res) {
    return res.render('quiz', {
      title: 'Quiz'
    });
  });

  app.get('/progress', function(req, res) {
    return res.render('progress', {
      title: 'Progress'
    });
  });

  app.post('/translate', function(req, res) {
    var data;
    data = req.body;
    console.log('clicked');
    if (data.errorCode) {
      data.text = "Please Enter Text for Translation";
    }
    beglobal.translations.translate(data, function(err, results) {
      if (err) {
        return console.log(err);
      }
      res.send({
        serverData: results
      });
    });
  });

  http.createServer(app).listen(app.get('port'), function() {
    return console.log('Express server listening on port ' + app.get('port'));
  });

}).call(this);
